# Some configuration needed for modifying the drawing record
FACTOR_CORRECTION = 0.00001
STOROKE_CONNECT_THERESHOLD=10
SMOOTHING_WEIGHT = 1.0/3
DEHOOK_THRESHOLD = 3
DEHOOK_ANGLE_THRESHOLD_BEG = 50
DEHOOK_ANGLE_THRESHOLD_END = 50
RESAMPLING_STROKE_THRESHOLD = 4
NUM_RESAMPLE = 1000
STROKE_PARTITION = 30
STROKE_PARTITION_CURV = 10
NUM_STROKES_AS_FEATURE = 4
NUM_TREES = 1000
NUM_CHARS_TO_SHOW = 3